---
title: "US & World Coronavirus Status Tracker"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard); library(gridExtra)
library(tidyr) ; library(tidyverse) ; library(scales)
library(ggplot2) ; library(dplyr) ; library(plotly)
```

```{r global, include=FALSE}

covid_data = read.csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv")

count_data = covid_data %>%
  filter(location == "United States" | location == "United Kingdom" |  location == "India" |
         location == "Japan" | location == "China" | location == "Brazil" |
         location == "Germany" | location == "Canada" | location == "Mexico" |
         location == "Italy") %>%
  select(location,date,total_cases,new_cases,total_deaths,new_deaths)

world_data = covid_data %>%
  filter(location == "World") %>%
  select(location,date,total_cases,new_cases,total_deaths,new_deaths)

last_row = world_data %>% 
  slice(n())
last_update = paste('Last Update:',last_row$date) 

countrygraphs = function(dtype){
   if(dtype==1){
    countryplot = ggplot(count_data, aes(x = as.Date(date), y = total_cases, col = location)) + geom_line() + ggtitle('Number of Total Cases Over Time per Country') +
      ylab('Total Number of Cases')
    
  } else if(dtype==2){
    countryplot = ggplot(count_data, aes(x = as.Date(date), y = new_cases, col = location)) + geom_line() + ggtitle('Number of New Cases Over Time per Country') +
      ylab('Number of New Cases')

  } else if(dtype==3){
    countryplot = ggplot(count_data, aes(x = as.Date(date), y = total_deaths, col = location)) + geom_line() + ggtitle('Number of Total Deaths Over Time per Country') +
      ylab('Total Number of Deaths')

  } else {
    countryplot = ggplot(count_data, aes(x = as.Date(date), y = new_deaths, col = location)) + geom_line() + ggtitle('Number of New Deaths Over Time per Country') +
      ylab('Number of New Deaths')
  }
  countryplotly = ggplotly(countryplot +
                             facet_wrap(~ location, ncol = 5) + 
                             theme(axis.text.x = element_blank(),
                                   axis.title.x = element_blank(),
                                   axis.title.y = element_blank()
                          ))
  return(countryplotly)
}

worldgraphs = function(dtype){
   if(dtype==1){
    worldplot = ggplot(world_data, aes(x = as.Date(date), y = total_cases)) + geom_line(color = "#00AFBB",size = 1) + 
      ggtitle('Number of Total Cases in the World Over Time') + xlab('Date (Months)') + ylab('Total Number of Cases')

  } else if(dtype==2){
    worldplot = ggplot(world_data, aes(x = as.Date(date), y = new_cases)) + geom_line(color = "#00AFBB",size = 1) + 
      ggtitle('Number of New Cases in the World Over Time') + xlab('Date (Months)') + ylab('Number of New Cases')

    
  } else if(dtype==3){
    worldplot = ggplot(world_data, aes(x = as.Date(date), y = total_deaths)) + geom_line(color = "#00AFBB",size = 1) + 
      ggtitle('Number of Total Deaths in the World Over Time') + xlab('Date (Months)') + ylab('Total Number of Deaths')

  } else {
    worldplot = ggplot(world_data,aes(x = as.Date(date), y = new_deaths)) + geom_line(color = "#00AFBB",size = 1) + 
      ggtitle('Number of New Deaths in the World Over Time') + xlab('Date (Months)') + ylab('Number of New Deaths')
  }
  worldplotly = ggplotly(worldplot + scale_y_continuous(labels = scales::comma))
  return(worldplotly)
}

```

Column {.sidebar data-width=350}
-----------------------------------------------------------------------

### Choose the type of data you would like to view by selecting from the following buttons: 

```{r}
radioButtons('dtype', 'Type:' , choices = c('Total Cases'=1,'New Cases'=2, 'Total Deaths'=3, 'New Deaths'=4), inline = FALSE)
```

Total Cases: Total confirmed cases of COVID-19.
  
New Cases: New confirmed cases of COVID-19.
  
Total Deaths: Total deaths attributed to COVID-19.
  
New Deaths: New deaths attributed to COVID-19.

```{r}
output$interact = renderText({'The plots are interactive. You can use the tools at the top right of the figure to manipulate the graphs! :)'})
output$update = renderText({last_update})
output$disclaimer = renderText({'This dashboard was made as an assignment for the course "Advanced Data Science for 
Biomedical Engineering" at Johns Hopkins University. This is not official health information and should not be used as such.'})

textOutput({'interact'})

textOutput({'update'})

textOutput({'disclaimer'})
```

Data comes from: [github.com/owid/covid-19-data/tree/master/public/data](https://github.com/owid/covid-19-data/tree/master/public/data).

For official COVID-19 data and dashboard visit the [Johns Hopkins Center for Systems Science and Engineering (CSSE)](https://systems.jhu.edu/).

Made by [Michael Breshock](https://mbreshock.github.io/).


Column {data-width=650}
-----------------------------------------------------------------------

### Country Data

```{r}
output$plot1 = renderPlotly({
dt=input$dtype
countrygraphs(dt)
})
plotlyOutput({'plot1'})
```

### World Data

```{r}
output$plot2 = renderPlotly({
  dt=input$dtype
  worldgraphs(dt)
})
plotlyOutput({'plot2'})
```

